### ISSUE TITLE
The link to the Reddit comment in the search result points to another comment

### ISSUE THREAD

**Issue by gmachine1** [camas/among-us#1]
**I am posting this issue here since https://github.com/camas/reddit-search/ has been disabled.**

As an example,
https://camas.unddit.com/#{"author":"michaelochurch","resultSize":100,"query":"surfeit%20of%20conscientiousness"}
gives
https://www.reddit.com/r/ChatGPT/comments/zmra9m/comment/j0ha4n0/?context=999
but the actual URL for the comment after navigating to it was:
https://www.reddit.com/r/ChatGPT/comments/zmra9m/comment/j0ha4n0/?utm_source=share&utm_medium=web2x&context=3

Based on what I've seen before, the `context` variable is always set to `999`. When the `context` variable is not set at all, it seems to navigate directly to the comment, which should be the desired behavior. As an example of this, https://www.reddit.com/r/ChatGPT/comments/zmra9m/comment/j0ha4n0/

This `context` parameter, when set, seems to navigate to some surrounding of that comment (perhaps one of its ancestors in the comment tree). My guess is setting it `999` will attempt to go `999` times up the tree which will practically speaking give the greatest ancestor.

Finally, thank you for creating such a helpful Reddit search service much better than the one that had existed before.

**Comment by camas** [comment]
Looks like a problem with new reddit. Old works fine
https://old.reddit.com/r/ChatGPT/comments/zmra9m/comment/j0ha4n0/?context=999

Ideally you'd be able to do the same with new. Not sure it's possible though
Going to the link without any params added https://www.reddit.com/r/ChatGPT/comments/zmra9m/comment/j0ha4n0/ then clicking `Show parent comments` gives a new `depth` parameter I hadn't seen before https://www.reddit.com/r/ChatGPT/comments/zmra9m/ive_been_talking_with_chatgpt_for_days_now_and_i/j0ha4n0/?context=8&depth=9 but going to that link directly doesn't work.

I'm also not the one hosting camas.unddit.com, I think that's u/gurnec. Hadn't really touched anything for a while even before it was taken down. There are probably similar frontends that are actively maintained if you look around r/pushshift
